### ISSUE TITLE
[0.97a RC11] Game crash upon clicking of OASQuestIntro icon in intel menu after forcing mod.info to 0.97a RC11

### ISSUE THREAD

**Issue by templeofshadow** [toopok4k3/Osiris-Alliance#1]
Below is the error line in my starsector.log:

`3135777 [Thread-2] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.IncompatibleClassChangeError: Expecting non-static method 'void com.fs.starfarer.api.impl.campaign.missions.hub.BaseHubMission.addStandardMarketDesc(java.lang.String, com.fs.starfarer.api.campaign.econ.MarketAPI, com.fs.starfarer.api.ui.TooltipMakerAPI, float)'
java.lang.IncompatibleClassChangeError: Expecting non-static method 'void com.fs.starfarer.api.impl.campaign.missions.hub.BaseHubMission.addStandardMarketDesc(java.lang.String, com.fs.starfarer.api.campaign.econ.MarketAPI, com.fs.starfarer.api.ui.TooltipMakerAPI, float)'
	at fi.toopok4k3.oas.quests.OasQuestIntro.addDescriptionForNonEndStage(OasQuestIntro.java:58) ~[?:?]
	at com.fs.starfarer.api.impl.campaign.missions.hub.BaseHubMission.addDescriptionForCurrentStage(BaseHubMission.java:758) ~[starfarer.api.jar:?]
	at com.fs.starfarer.api.impl.campaign.missions.hub.BaseHubMission.createSmallDescription(BaseHubMission.java:2343) ~[starfarer.api.jar:?]
	at com.fs.starfarer.campaign.comms.v2.EventsPanel.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.campaign.comms.v2.EventsPanel.actionPerformed(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o0O0.buttonPressed(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.int.Ò00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.int.processInput(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o0O0.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.g$Oo.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o000.dispatchEventsToChildren(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o000.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.g.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o000.dispatchEventsToChildren(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o000.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o000.dispatchEventsToChildren(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o000.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.campaign.comms.v2.EventsPanel.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o000.dispatchEventsToChildren(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o000.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.campaign.comms.return.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o000.dispatchEventsToChildren(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o000.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.newui.o0OO.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o000.dispatchEventsToChildren(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o000.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.O.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.newui.L.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o000.dispatchEventsToChildren(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o000.processInputImpl(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.campaign.CampaignState.processInput(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source) ~[port_obf.jar:?]
	at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]`

Method to reproduce error:
(Presupposes forcing mod.info game version to 0.97a RC11)
1. Accept the bar mission
2. Open intel tab
3. Click on mission
4. Crash to desktop

Some others are mentioning this happening to them too on the forum.
Tried to look into it a bit myself, but I'm not super familiar with Java nor with Starsector's API, so I basically got nowhere.
@toopok4k3 I don't know if you're still around to work on this mod, but if you are, it'd be cool if you'd at least give some kind of workaround.

Let me know if you need any additional information.

**Comment by toopok4k3** [comment]
This has been fixed. Search for a hotfix .jar in the unofficial starsector discord server for the 0.96 version of the mod. I don't have an official update for the 0.97 version of starsector up yet hence why I have not uploaded it to the official starsector forum yet.
